# Generated by Django 3.1.5 on 2021-01-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_room_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
