# Generated by Django 3.1.5 on 2021-01-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_people',
            field=models.IntegerField(default=0),
        ),
    ]
